name: Erebus Interface CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          
      - name: Run tests
        run: |
          python tests/run_tests.py
          
      - name: Save test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            tests/vision_records/
            evolution_records/
            
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Start Flask server
        run: |
          source .venv/bin/activate
          python app.py &
          
      - name: Record deployment
        run: |
          echo "Deployment at $(date)" >> deployment_log.txt
          echo "Interface manifested successfully" >> deployment_log.txt